package io.github.adelinosousa.gradle.tasks

import io.github.adelinosousa.gradle.github.GhBinaryResolver
import org.gradle.api.DefaultTask
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.UntrackedTask
import java.io.File

@UntrackedTask(because = "Writes to Gradle user home which is outside the project directory")
public abstract class GhCliAuthInstallTask : DefaultTask() {

    internal companion object {
        const val TASK_NAME: String = "ghCliAuthInstall"
        const val TASK_GROUP: String = "gh-cli-auth"
        const val INIT_SCRIPT_NAME: String = "gh-cli-auth.init.gradle.kts"
    }

    @get:Input
    public abstract val githubOrg: Property<String>

    @get:Input
    public abstract val gradleUserHomeDir: Property<String>

    @TaskAction
    public fun install() {
        val gradleUserHome = File(gradleUserHomeDir.get())
        val ghBin = GhBinaryResolver.resolve()

        val initDir = gradleUserHome.resolve("init.d").apply { mkdirs() }
        val initScript = initDir.resolve(INIT_SCRIPT_NAME)

        initScript.writeText(generateInitScript(githubOrg.get(), ghBin))

        logger.lifecycle("Installed init script: ${initScript.absolutePath}")
    }

    internal fun generateInitScript(org: String, ghBinary: String): String = """
        |// Generated by gh-cli-auth Gradle plugin — do not edit manually.
        |// To remove, run: ./gradlew ghCliAuthUninstall
        |
        |beforeSettings {
        |    val token = providers.exec {
        |        commandLine("$ghBinary", "auth", "token")
        |    }.standardOutput.asText.map { it.trim() }
        |
        |    pluginManagement {
        |        repositories {
        |            gradlePluginPortal()
        |            maven {
        |                name = "GitHubPackages"
        |                url = uri("https://maven.pkg.github.com/$org/*")
        |                credentials {
        |                    username = ""
        |                    password = token.get()
        |                }
        |            }
        |        }
        |    }
        |}
    """.trimMargin()
}
