package io.github.adelinosousa.gradle.tasks

import io.github.adelinosousa.gradle.github.GhBinaryResolver
import io.github.adelinosousa.gradle.plugins.GhCliAuthBase.Companion.GH_CLI_EXTENSION_NAME
import org.gradle.api.logging.Logger
import org.gradle.api.logging.Logging
import java.io.File

internal object GhCliAuthInstaller {
    internal const val INIT_SCRIPT_NAME: String = "gh-cli-auth.init.gradle.kts"

    private val logger: Logger = Logging.getLogger(GH_CLI_EXTENSION_NAME)

    internal fun installIfNeeded(gradleUserHome: File, githubOrg: String): Boolean {
        val initScript = initScriptFile(gradleUserHome)
        val desired = generateInitScript(githubOrg, GhBinaryResolver.resolve())

        if (initScript.exists() && initScript.readText() == desired) {
            logger.debug("gh-cli-auth init script already up-to-date: ${initScript.absolutePath}")
            return false
        }

        initScript.parentFile.mkdirs()
        initScript.writeText(desired)
        logger.lifecycle("Installed init script: ${initScript.absolutePath}")
        return true
    }

    internal fun initScriptFile(gradleUserHome: File): File =
        gradleUserHome.resolve("init.d").resolve(INIT_SCRIPT_NAME)

    internal fun generateInitScript(org: String, ghBinary: String): String = """
        |// Generated by gh-cli-auth Gradle plugin — do not edit manually.
        |// To remove, run: ./gradlew ghCliAuthUninstall
        |
        |beforeSettings {
        |    val token = providers.exec {
        |        commandLine("$ghBinary", "auth", "token")
        |    }.standardOutput.asText.map { it.trim() }
        |
        |    pluginManagement {
        |        repositories {
        |            gradlePluginPortal()
        |            maven {
        |                name = "GitHubPackages"
        |                url = uri("https://maven.pkg.github.com/$org/*")
        |                credentials {
        |                    username = ""
        |                    password = token.get()
        |                }
        |            }
        |        }
        |    }
        |
        |    dependencyResolutionManagement {
        |        repositories {
        |            maven {
        |                name = "GitHubPackages"
        |                url = uri("https://maven.pkg.github.com/$org/*")
        |                credentials {
        |                    username = ""
        |                    password = token.get()
        |                }
        |            }
        |        }
        |    }
        |}
    """.trimMargin()
}
