name: PR Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        shell: bash
        run: ./gradlew build --info
        env:
          GH_TOKEN: ${{ secrets.TEST_PAT }}

  code-scanning:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java-kotlin

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        shell: bash
        run: ./gradlew build -x test -x functionalTest --no-build-cache --rerun-tasks
        env:
          GH_TOKEN: ${{ secrets.TEST_PAT }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
